spring.application.name=scpminmemory

server.port=${PORT:8080}
app.security.mode=${MODE:production}
#requiresendgrid.from.email=parthsethi29@gmail.com
#sendgrid.from.name=parht
#sendgrid.api.key=${SENDGRID_API_KEY}
#sendgrid.timeout=10000

# EMAIL CONFIGURATION
spring.mail.host=${MAINURL:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${EMAIL:arvinderpalsingh2321@gmail.com}
spring.mail.password=${APP_PASS:jajjfudjbjoujkac}
#  ${APP_PASS:jajj fudj bjou jkac}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.profiles.active=dev

#actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Server Configuration
server.error.include-message=always
server.error.include-stacktrace=on-param
server.error.include-binding-errors=always
server.error.include-exception=true

# CORS - Production domains
#cors.allowed-origins=${URL:https://scpms-inmemory-backend.onrender.com,http://127.0.0.1:5173}
spring.base.url=${URL}
#spring.base.url=https://scpms-in-memory-frontend.onrender.com

# application.properties
#spring.security.oauth2.authorizationserver.issuer=https://scpms-inmemory-backend.onrender.com
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH_ISSUER_URI}
## Logging
logging.level.userService=INFO

spring.registerClient.clientId=${CLIENT_ID}
spring.registerClient.password=${CLIENT_SECRET}
#spring.registerClient.redirectUri=${REDIRECT_URI:https://scpms-frontend-nrcx.onrender.com/callback}
#spring.registerClient.postLogoutRedirectUri=${POST_LOGOUT_URI:https://scpms-frontend-nrcx.onrender.com/}
spring.registerClient.redirectUri=${REDIRECT_URI:http://localhost:5173/callback}
#spring.registerClient.redirectUri=https://scpms-in-memory-frontend.onrender.com/callback
#spring.registerClient.postLogoutRedirectUri=https://scpms-in-memory-frontend.onrender.com
spring.registerClient.postLogoutRedirectUri=${POST_LOGOUT_URI}

#cors.allowed-origins=${URL_ORIGIN:http://localhost:8080,http://127.0.0.1:5173}
#cors.allowed-origins=${URL}

#to allow different domine requests for exmaple localhost to onrender.com
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true



# LOGGING
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.maximum-pool-size=10