spring.application.name=scpminmemory

server.port=${PORT:8080}
app.security.mode=${MODE:production}


# EMAIL CONFIGURATION
spring.mail.host=${MAINURL:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${EMAIL}
spring.mail.password=${APP_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.profiles.active=dev
#actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# ServerConfiguration
server.error.include-message=always
server.error.include-stacktrace=on-param
server.error.include-binding-errors=always
server.error.include-exception=true
spring.telegram.token=${TOKEN}
spring.devtools.restart.enabled=false
spring.main.lazy-initialization=true
#logging.level.userService=INFO
l
spring.registerClient.clientId=${CLIENT_ID:abhi}
spring.registerClient.password=${CLIENT_SECRET:}
spring.registerClient.redirectUri=${REDIRECT_URI:}
spring.backend.url=${BACKEND_URL:}
spring.frontend.url=${FRONTEND_URL:}
spring.base.url=${spring.frontend.url:}
spring.registerClient.postLogoutRedirectUri=${POST_LOGOUT_URI:}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH_ISSUER_URI}

##to allow different domine requests for exmaple localhost to onrender.com
#server.servlet.session.cookie.same-site=Lax
#server.servlet.session.cookie.secure=false


# LOGGING
#logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.web=DEBUG

#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.maximum-pool-size=10